### PR TITLE
New Items, refactored view classes into files, item icons, and updated/tested libraries

### PR DESCRIPTION
**Pull request by NoahFrank**
Changes:
- Added items, mostly highly traded/valuable like matrices/encryptions/antique summoning stones/ambergris/precursors/etc
- Added item icons for new items (not 100% loving the styling but it's nice and does require additional API call)
- Refactored view classes into files inside the `gw2pc/view` directory
- Cleaned up `views.py` as much as possible
- Made the django HTML templates more generic instead of carefully curated items like MC/Ecto
- Updated to latest version of available (python+js) libraries and everything worked (excluding zappa and django-s3-storage because I couldn't test them)

Questions:
- Are the editorial market explanations tailored to each item required for my PR to be accepted? As it stands the editorialization I added is lacking.
- I personally prefer opening a link in a new tab by default, so I experimented in this PR with this idea.  Mixing the behavior of opening a new tab or redirecting to the link should be standardized as one or the other across the entire site.  I can make these changes if you have an opinion, basically wanted to get your thoughts on the matter.

Caveats:
- I tested these changes in python 3.10 and 3.8 on Win10 and Ubuntu20. I haven't tested these changes in your AWS deploy environment, so feel free to rollback any library version changes or other weird issues that might occur.

Fix:
- Corrected url path from [https://gw2pc.com/legendary/](https://gw2pc.com/legendary/) to [https://gw2pc.com/leg/](https://gw2pc.com/leg/) for legendary weps ->[here](https://github.com/NoahFrank/gw2pc/blob/fb3d46b29fb1a294d5869e87867845e64b677663/templates/gw2pc/legendaries.html#L9)<-

### CODE REVIEW

**Comment by otc-cirdan** [comment]
I'm getting some error about buckets from Zappa when I try to deploy anything, including the existing version of the code. I'll deploy this to staging and ask you to test it, but I need to figure out that issue first.

**Comment by otc-cirdan** [comment]
As it turns out, reading the error message explains the error message.

@NoahFrank , your code is live at https://dev.gw2pc.com/ , please test it and see if everything is working as intended.

I had to bump a few versions in etc/requirements.txt, please update your PR to take these into account. The old version of django-s3-storage isn't compatible with Django 4.0:
```
-zappa==0.53.0
+zappa==0.54.2
-django-s3-storage==0.13.4
+django-s3-storage==0.13.7
```

I'll review your pull request more substantively in the coming days.

**Comment by otc-cirdan** [comment]
> I personally prefer opening a link in a new tab by default, so I experimented in this PR with this idea. Mixing the behavior of opening a new tab or redirecting to the link should be standardized as one or the other across the entire site. I can make these changes if you have an opinion, basically wanted to get your thoughts on the matter.

I do not think that links should open in a new tab by default. Middle-click / ctrl-click is a common shortcut to open a link in a new tab if the user wants to, but I think that opening links in a new tab by default is often surprising and undesired, and does not come with a commonly-known way for the user to see that the link will open in a new tab before clicking it, and to choose to open that link in the same tab if they desire.

There is maybe the example where the user wants to open the bltc links for a number of items at once to get some more detailed analysis. However, it's easy for users to hold down ctrl or use the middle button in that case, while it's not possible to force a link to open in the same tab if we choose to open a new tab by default.

> Are the editorial market explanations tailored to each item required for my PR to be accepted? As it stands the editorialization I added is lacking.

For items that are very simple - if they routinely trade at 90% and there isn't much more to say about them - then it's fine to just say that. For Gen 3s I assume they are pretty similar to Gen 1s and the explanation can probably safely be copy/pasted.

**Comment by NoahFrank** [comment]
Looks like everything is working in the dev environment!  I noticed an issue with my fix mentioned in the PR so I made another commit to address it.


> I do not think that links should open in a new tab by default.

I have also remove the default opening in new tab behavior!

**Comment by otc-cirdan** [comment]
9c05aaa pushed to https://staging.gw2pc.com/ (and dev)

**Comment by NoahFrank** [comment]
Did you have a chance to review the changes in more detail?  Any stability issues hosting the dev/staging servers?

**Comment by otc-cirdan** [comment]
I don't see any major issues, but there are a few additional dependency version updates that are needed which I mentioned in the review comments above

**Comment by NoahFrank** [comment]
Okay cool, I updated the dependency versions, let me know what else is needed before PR approval!

**Pull request merged**
